version: '2.1'

services:
  analytics:
    build: .
    environment:
      PROJECT_ID:
      PRIVATE_KEY_ID:
      PRIVATE_KEY:
      CLIENT_EMAIL:
      CLIENT_ID:
      CLIENT_X509_CERT_URL:

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: $SUBNET
